01: fibonacci numbers
ImBigman/go-core pull request #1
Opened 2021-04-20 19:33 UTC by ImBigman

**Задание.**
Разработка приложения для подсчёта чисел Фибоначчи.

**Требования.**
Максимальный номер числа Фибоначчи не должен превышать 20.

**Задача №1.**
Создать стандартную структуру каталогов с исполняемыми и подключаемыми пакетами. Разработать пакет, экспортирующий функцию, позволяющую вычислить число Фибоначчи по его номеру.

**Задача №2.**
Разработать исполняемый пакет, который бы вызывал функцию подсчёта числа Фибоначчи для нескольких чисел и печатал результат в консоль.
Номера чисел могут быть заложены в код исполняемого пакета.

2021-04-21 05:22 UTC, DmitriyVTitov requested changes
С почином, ваша работа - первая.
Начал писать рекомендации по именам, без этого не обойтись )
https://github.com/hardcode-dev/go-core-2/blob/master/doc/%D0%98%D0%BC%D0%B5%D0%BD%D0%B0.md

2021-04-21 05:22 UTC, DmitriyVTitov commented on 01-first-lesson/pkg/fibo/fibo.go
> +func FiboNumbers(n int) {
В Go не принято добавлять имя пакета к именам функций и типов.
fibo.FiboNumbers() - не очень.
fibo.Number() - логично и очень.

2021-04-21 05:22 UTC, DmitriyVTitov commented on 01-first-lesson/pkg/fibo/fibo.go
> +	var fiboArray [20]int = [20]int{0, 1}
для Go идиоматичней имя массива `a`

2021-04-21 05:22 UTC, DmitriyVTitov commented on 01-first-lesson/go.mod
> +go 1.16
ага

2021-04-21 05:22 UTC, DmitriyVTitov commented on 01-first-lesson/pkg/fibo/fibo.go
> +func FiboNumbers(n int) {
Для чего нужен этот пакет? Чтобы я мог им воспользоваться для вычисления числа Ф. При этом функция не возвращает мне никакого числа, а просто что-то печатает на экране. Вы уверены, что мне это нужно и я для этого просил вас разработать пакет?

2021-04-21 05:22 UTC, DmitriyVTitov commented on 01-first-lesson/pkg/fibo/fibo.go
> +}
Обработкой полученных данных (печать и прочее) занимается вызывающий код, т.е. пакет main.

2021-04-21 05:22 UTC, DmitriyVTitov commented on 01-first-lesson/pkg/fibo/fibo.go
> +	}
т.е. какое бы число я не передал будет считаться всегда 20 элементов последовательности? очень неэффективно.
в алгоритме нигде не используется `n`!

2021-04-21 05:37 UTC, ImBigman commented on 01-first-lesson/go.mod
> +go 1.16
его тоже убрать? в описании было только про `go.sum`

2021-04-21 05:44 UTC, ImBigman commented on 01-first-lesson/pkg/fibo/fibo.go
> +	}
я изначально хотел сделать передачу `n` для указания длинны массива и его  же передачу в условие ` i < n`, но Go не позволяет передавать переменные в инициализацию массивов

2021-04-21 06:00 UTC, DmitriyVTitov commented on 01-first-lesson/go.mod
> +go 1.16
не, это как раз хорошо и по делу :)

2021-04-21 06:01 UTC, DmitriyVTitov commented on 01-first-lesson/pkg/fibo/fibo.go
> +	}
а в условие цикла позволяет?
тут ОК, это первое занятие, не принципиально. мне не нравится, что функция не возвращает результат а вместо этого что-то печатает

2021-04-21 07:06 UTC, ImBigman commented on 01-first-lesson/pkg/fibo/fibo.go
> +	}
"мне не нравится, что функция не возвращает результат а вместо этого что-то печатает" © это исправим

2021-04-21 20:45 UTC, DmitriyVTitov requested changes
Опять не принимаю. Я скачал ваш пакет и хочу вызвать функцию как-нибудь так:
fibo.Num(5).
Никакие массивы не нужны.
Давайте ещё одну итерацию.

2021-04-21 20:45 UTC, DmitriyVTitov commented on 01-first-lesson/pkg/fibo/fibo.go
> +}
ещё страннее )
вот я скачал ваш пакет, чтобы посчитать число Ф, а тут функция:
1. Numbers - во множественном числе, а почему?
2. принимает два аргумента - это как? я же просто передаю номер и получаю число с этим номером в последовательности

да и вообще: зачем тут какой-то массив? тут же просто цикл, который складывает два предыдущих значения. сделайте две переменных-контейнера и храните в них промежуточные результаты.
массив имеет смысл для применения метода динамического программирования, но вы его тут не используете (кэширование результатов для последующего мгновенного использования).

2021-04-24 12:16 UTC, DmitriyVTitov approved these changes
OK, теперь принимаю.

2021-04-24 12:16 UTC, DmitriyVTitov commented on 01-first-lesson/cmd/fibonacci/main.go
> +func print(c int) {
плохое имя, поскольку вообще не говорит ничего.
кстати, в Go есть встроенная функция print().
https://pkg.go.dev/builtin#print

2021-04-24 12:16 UTC, DmitriyVTitov commented on 01-first-lesson/cmd/fibonacci/main.go
> +
лишняя пустая строка

2021-04-24 12:16 UTC, DmitriyVTitov commented on 01-first-lesson/cmd/fibonacci/main.go
> +
лишняя пустая строка

2021-04-24 12:16 UTC, DmitriyVTitov commented on 01-first-lesson/pkg/fibo/fibo.go
> +		b = d
эквивалентно
`b, c = c, b+c`

2021-04-24 16:34 UTC, ImBigman commented on 01-first-lesson/pkg/fibo/fibo.go
> +		b = d
я понимаю, думал для читаемости

2021-04-24 16:55 UTC, ImBigman commented on 01-first-lesson/cmd/fibonacci/main.go
> +func print(c int) {
https://github.com/ImBigman/go-core/pull/1/files

2021-04-24 17:27 UTC, DmitriyVTitov commented on 01-first-lesson/cmd/fibonacci/main.go
> +func resultFor(c int) {
тоже так себе имя.
что оно означает?
и самое главное, эта функция никакого результата ни для чего не возвращает. она его печатает.
`printFiboNum` какой-нибудь.

2021-04-28 05:13 UTC, merged