02: init
ImBigman/go-core pull request #2
Opened 2021-05-04 17:25 UTC by ImBigman

**Задача №1**
Создайте приложение со стандартной структурой каталогов: cmd и pkg. Скопируйте в приложение пакет «crawler» из каталога GoSearch репозитория курса.

**Задача №2**
Создайте исполняемый пакет, который бы при запуске использовал пакет «crawler» для сканирования сайтов «go.dev» и «golang.org». Результат сканирования сайтов нужно объединить.

**Задача №3**
После окончания сканирования, если пользователь ввел какое-либо слово в флаге «s», приложение должно напечатать все ссылки, где это слово встречается. Пример вызова программы:
 
`gosearch –s documents`
 
Для обработки флагов вызова используйте пакет «flag».

2021-05-05 07:17 UTC, DmitriyVTitov requested changes
Я не понял логики работы, слишком сложно для такой задачи.
Посмотрите ролик с разбором задания и сравните результат. Я ни в коем случае не предлагаю повторять за мной, но самый крутой код на Go - самый простой и понятный.

2021-05-05 07:17 UTC, DmitriyVTitov commented on 02-second-lesson/cmd/scanner/main.go
> +	res := append(d, e...)
я бы скорее ожидал увидеть массив url для сканирования и цикл с итерацией. ваш вариант сложно масштабировать.

2021-05-05 07:17 UTC, DmitriyVTitov commented on 02-second-lesson/cmd/scanner/main.go
> +	}
отсутствует, ну и что? по мне это не ошибка, но не настаиваю

2021-05-05 07:17 UTC, DmitriyVTitov commented on 02-second-lesson/cmd/scanner/main.go
> +	word := flag.Arg(0)
что-то странное, я никогда flag.Arg() не использовал.
почему не сделать `s` строковым параметром?
из документации:
```
// Example 1: A single string flag called "species" with default value "gopher".
var species = flag.String("species", "gopher", "the species we are studying")
```

2021-05-05 07:17 UTC, DmitriyVTitov commented on 02-second-lesson/cmd/scanner/main.go
> +type doc = crawler.Document
зачем? чем плох оригинальный тип?

2021-05-05 07:17 UTC, DmitriyVTitov commented on 02-second-lesson/cmd/scanner/main.go
> +type pages = []doc
такое объявление нового типа имеет смысл либо для читаемости, либо чтобы объявить методы.
тут не видно ничего из этого.

2021-05-05 07:17 UTC, DmitriyVTitov commented on 02-second-lesson/cmd/scanner/main.go
> +type search struct {
имя неудачное и сам тип данных выглядит лишним.
имя типа не должно быть глаголом.

2021-05-05 07:17 UTC, DmitriyVTitov commented on 02-second-lesson/go.mod
> +require golang.org/x/net v0.0.0-20210428140749-89ef3d95e781
сделайте один модуль в корне репозитория

2021-05-05 07:17 UTC, DmitriyVTitov commented on 02-second-lesson/cmd/scanner/main.go
> +	res, err := service.Scan(s.url, s.depth)
пересоздавать службу для каждого сайта неразумно

2021-05-05 07:17 UTC, DmitriyVTitov commented on 02-second-lesson/cmd/scanner/main.go
> +}
Я не могу уследить за мыслью. Что делают все эти функции? Ищут наличие строки в массиве документов?
Для этого должно быть достаточно трех строк.
Слишком сложно.

2021-05-06 08:11 UTC, ImBigman commented on 02-second-lesson/cmd/scanner/main.go
> +type search struct {
ок, переименую, не хочу прерикаться, но search это имя существительное

2021-05-06 08:14 UTC, ImBigman commented on 02-second-lesson/go.mod
> +require golang.org/x/net v0.0.0-20210428140749-89ef3d95e781
пока первый урок не слит был, не могу такого сделать

2021-05-06 08:27 UTC, ImBigman commented on 02-second-lesson/cmd/scanner/main.go
> +}
**pagesContains** - добавляет документ в слайс, если в нем есть искомое.
**returnLinks** - возвращал на экран массив `порядковый номер: ссылка на сайт`  - по ТЗ _"приложение должно напечатать все ссылки, где это слово встречается."_
**concateFields** - склеивал заголовок и url докемента + менял с заглавной на строчную первые буквы, для поиска по ним

 - последний и первый передулаю - я все еще не могу понять насколько громостким может быть код, который во Го считается читаемым...

2021-05-06 13:22 UTC, DmitriyVTitov commented on 02-second-lesson/cmd/scanner/main.go
> +type search struct {
но это же как бы процесс - "поиск"
тип данных всё таки должен быть больше про объект.
вот я просто смотрю на эту структуру: у неё поля глубина и URL. вот что она должна означать?
поиск глубины на сайте?
в конце концов, это не про поиск а про сканирование (scraping, crawling)

2021-05-06 13:26 UTC, DmitriyVTitov commented on 02-second-lesson/cmd/scanner/main.go
> +}
ОК, я не сомневался, что вы хорошо ориентируетесь в своём коде. Но решение такой несложной задачи я должен понять читая "по диагонали". Тут же мне приходится перескакивать вперед назад, пытаться понять смысл функций.
Вам самому выражение "возвращал на экран" не кажется странным?
Понятный код на Go будет значительно меньше, весь поиск и вывод результатов на экран будет в одном цикле в функции main(). То есть максимально топорно - это в стиле Go.
Я бы решил так:
https://github.com/hardcode-dev/go-core-2/blob/master/homeworks/03-gosearch-v1/cmd/gosearch/gosearch.go

2021-05-06 13:29 UTC, DmitriyVTitov commented on 02-second-lesson/cmd/scanner/main.go
> +}
И да, четких критериев понятности и чистоты кода нет. Чем больше мы пишем код и смотрим как это делают признанные специалисты, тем лучше получается. Единственный сколько-нибудь объективные критерии - простота считывания кода и простота ментальной модели.
Чем проще и то и другое, тем лучше.

2021-05-07 07:47 UTC, DmitriyVTitov approved these changes
ОК, но учтите замечания.

2021-05-07 07:47 UTC, DmitriyVTitov commented on 02-second-lesson/cmd/scanner/main.go
> +func (s targets) Scan() ([]crawler.Document, error) {
**t** **t**argets

2021-05-07 07:47 UTC, DmitriyVTitov commented on 02-second-lesson/cmd/scanner/main.go
> +func (s targets) Scan() ([]crawler.Document, error) {
Я бы сказал, что методы здесь тоже выглядят немного избыточно. Достаточно было бы просто функций.

2021-05-07 07:47 UTC, DmitriyVTitov commented on 02-second-lesson/cmd/scanner/main.go
> +		res, _ := service.Scan(v.url, v.depth)
Игнорировать ошибки нельзя!

2021-05-07 07:47 UTC, DmitriyVTitov commented on 02-second-lesson/cmd/scanner/main.go
> +func (s targets) Scan() ([]crawler.Document, error) {
ошибка в принципе не может возникнуть, зачем её возвращать?

2021-05-07 08:40 UTC, ImBigman commented on 02-second-lesson/cmd/scanner/main.go
> +func (s targets) Scan() ([]crawler.Document, error) {
Верно, просто хотел попрактиковаться.

2021-05-07 08:47 UTC, merged