03: create index
ImBigman/go-core pull request #3
Opened 2021-05-10 18:43 UTC by ImBigman

**Задача №1.**
Создать обратный индекс для документов. Разместить индекс в пакете «index». Ключом индекса будет каждое слово из описания ссылок, значением – номер документа.
После сканирования сайтов все найденные ссылки должны храниться в виде структуры следующего вида:
```
type Document struct {
    ID    int
    URL   string
    Title string
}
```
Проиндексированные документы должны храниться в массиве документов и объекте из пакета «index». При этом для каждого документа нужно добавить его номер – поле в структуре данных вместе с URL и Title.
Массив документов должен быть отсортирован по номерам, используя сортировку из стандартной библиотеки.

**Задача №2.**
Переделать метод поисковой выдачи на использование индекса.
Для поиска по индексу приложение должно импортировать поисковый индекс из пакета «index» как зависимость и искать по индексу, а не по массиву документов. Поиск по индексу должен выдавать номера документов (поле в структуре данных документа).

**Задача №3.**
После получения номеров документов из индекса нужно использовать бинарный поиск по отсортированному ранее массиву документов (по номерам документов).
Можно воспользоваться стандартной библиотекой или написать свою реализацию.

2021-05-10 23:43 UTC, DmitriyVTitov requested changes
Ничего не понимаю. Зачем вам массив уникальных строк и чисел?

2021-05-10 23:43 UTC, DmitriyVTitov commented on 03-third-lesson/cmd/scanner/main.go
> +	res := resources.Scan()
для чего метод? ведь состояние не меняется.
метод только смущает.
у метода пустая сигнатура и догадаться что он делает сложно, обычная функция читалась бы куда как лучше.

2021-05-10 23:43 UTC, DmitriyVTitov commented on 03-third-lesson/cmd/scanner/main.go
> +type targets []target
считаю эти типы лишними, не вижу в них смысла

2021-05-10 23:43 UTC, DmitriyVTitov commented on 03-third-lesson/pkg/index/index.go
> +func Make(d []crawler.Document) map[string][]int {
у экспортируемого объекта должен быть комментарий
создать что?

2021-05-10 23:43 UTC, DmitriyVTitov commented on 03-third-lesson/pkg/index/index.go
> +func Make(d []crawler.Document) map[string][]int {
кстати, вот для `map[string][]int` я бы ввёл тип данных
`type Index map[string][]int` - читалось бы лучше

2021-05-10 23:43 UTC, DmitriyVTitov commented on 03-third-lesson/pkg/index/index.go
> +	stringMap := make(map[string][]int)
это не stringMap, это что-то ведь конкретное. это индекс же, правильно?

2021-05-10 23:43 UTC, DmitriyVTitov commented on 03-third-lesson/pkg/index/index.go
> +		stringSlice = uniqString(stringSlice)
вот такие имена ни о чём не говорят, следить за мыслью очень сложно

2021-05-10 23:43 UTC, DmitriyVTitov commented on 03-third-lesson/pkg/index/index.go
> +		// формирую слайс из документов нового типа данных
комментарии не должны отвечать на вопрос "что?", они должны отвечать на вопрос "зачем?"

2021-05-10 23:43 UTC, DmitriyVTitov commented on 03-third-lesson/pkg/index/index.go
> +// два метода для создания слайсов с уникальными значениями для строк и чисел
а зачем? не понимаю.

2021-05-10 23:43 UTC, DmitriyVTitov commented on 03-third-lesson/pkg/index/index.go
> +	list := []string{}
опять дополнительные переменные.
представьте, что Яндекс начнёт так свой индекс переливать туда-сюда!

2021-05-10 23:43 UTC, DmitriyVTitov commented on 03-third-lesson/pkg/index/index.go
> +	}
не проверял, но почти уверен что этот "бинарный поиск" выдаст неправильный результат, если "search" отсутствует

2021-05-10 23:43 UTC, DmitriyVTitov commented on 03-third-lesson/pkg/index/index.go
> +func binarySearch(d []Document, search int) (Document, error) {
имя "search" mу вас универсальное :)
для аргумента ну вот вообще не то! `n` гораздо лучше

2021-05-11 18:00 UTC, ImBigman commented on 03-third-lesson/pkg/index/index.go
> +// два метода для создания слайсов с уникальными значениями для строк и чисел
когда  в документе несколько раз встречается искомое слово,  как пример - "go": [ 1 1 1 ] - получается он вернет несколько ссылок.

2021-05-11 19:45 UTC, ImBigman commented on 03-third-lesson/pkg/index/index.go
> +	}
он не может отсутсвовать - функция принимает инт, так как туда передаются ID страниц из индекса в цикле, а вот проверки что массив может быть пустой небыло.

2021-05-11 21:18 UTC, DmitriyVTitov commented on 03-third-lesson/pkg/index/index.go
> +// два метода для создания слайсов с уникальными значениями для строк и чисел
ОК, понятно. Но для этой цели гораздо проще и понятней будет хэш-таблица - `map`.

2021-05-11 21:21 UTC, DmitriyVTitov commented on 03-third-lesson/pkg/index/index.go
> +	}
Функция бинарного поиска не должна знать ничего о том, что ей будет передаваться. Вот я передам ID который не назначен ни одному документу, и всё. Она вернёт что-то посередине. Например у документов ID 90, 100, 101 ... А все промежуточные удалены, а я передам 95.
Бинарный поиск должен делать ровно это, не беря в расчёт обстоятельства конкретной задачи.

2021-05-12 09:29 UTC, DmitriyVTitov approved these changes
ОК, на мой взгляд лучше, но есть куда расти :)
Индекс стоит сделать службой, т.е. объявить тип в виде структуры, сделать конструктор и методы. Тем более, что занятие по ООП уже было.
Но прогресс очевиден, качество кода растёт. А это даже важнее чем правильные синтаксические конструкции и прочее.

2021-05-12 09:29 UTC, DmitriyVTitov commented on 03-third-lesson/cmd/scanner/main.go
> +	docIndex := index.Make(res)
по "гошному" было бы `ind`

2021-05-12 09:29 UTC, DmitriyVTitov commented on 03-third-lesson/cmd/scanner/main.go
> +		docs, error := index.Search(docIndex[*sFlag], index.Documents)
какая в принципе может быть ошибка при поиске?

2021-05-12 09:29 UTC, DmitriyVTitov commented on 03-third-lesson/cmd/scanner/main.go
> +		} else {
зачем тут else?

2021-05-12 09:29 UTC, DmitriyVTitov commented on 03-third-lesson/cmd/scanner/main.go
> +		} else {
читается плохо, лучше уж `if err == nil`
но, вообще, на ошибку должно быть какое-то действие, а тут только надпись.
это, как раз, и есть следствие того, что ошибка при поиске надуманная.
в чём ошибка? ничего не нашёл? ну и ладно!

2021-05-12 09:29 UTC, DmitriyVTitov commented on 03-third-lesson/cmd/scanner/main.go
> +	}
ещё один else - вообще ничего не понятно, старайтесь else не использовать вообще

2021-05-12 09:29 UTC, DmitriyVTitov commented on 03-third-lesson/cmd/scanner/main.go
> +}
вот вполне такая аккуратная функция

2021-05-12 09:29 UTC, DmitriyVTitov commented on 03-third-lesson/pkg/index/index.go
> +var Documents []Document
глобальная переменная явно не нужна

2021-05-12 09:29 UTC, DmitriyVTitov commented on 03-third-lesson/pkg/index/index.go
> +}
типы (модель данных) выносите в начало пакета

2021-05-12 09:29 UTC, DmitriyVTitov commented on 03-third-lesson/pkg/index/index.go
> +var Documents []Document
Вот для индекса, как раз, можно было создать структуру с полями для индекса и массива документов и сделать функции методами. Это было бы правильно, поскольку индекс хранит своё состояние. Вспоминайте последнее занятие про ООП - как раз про это.

2021-05-12 09:29 UTC, DmitriyVTitov commented on 03-third-lesson/pkg/index/index.go
> +}
функция выглядит лишней, как по мне

2021-05-12 20:28 UTC, merged