05: add storage pkg
ImBigman/go-core pull request #5
Opened 2021-05-22 18:44 UTC by ImBigman

**Задача №1.**

- Разработать механизм записи полученных от сканера данных в файл. Механизм должен использовать io.Writer в качестве аргумента. Формат представления данных для хранения выбирайте на своё усмотрение.

**Задача №2.**

- Загрузка данных из файла при старте поисковика.
- Если файл с данными существует, то сканировать сайты не нужно, нужно загрузить данные из файла.
- В процессе обязательно должен использоваться io.Reader.

2021-05-23 12:21 UTC, DmitriyVTitov requested changes
Обработкой ошибок должен заниматься вызывающий код. А уж вызов паники в импортируемом пакете - вообще антипаттерн и я про это не раз говорил.

2021-05-23 12:21 UTC, DmitriyVTitov commented on 05-fifth-lesson/pkg/storage/storage.go
> +func Exrtact() []crawler.Document {
1. У экспортируемой функции должен быть комментарий.
2. Функция работает с файлами и не возвращает ошибку?

2021-05-23 12:21 UTC, DmitriyVTitov commented on 05-fifth-lesson/pkg/storage/storage.go
> +}
Так делать нельзя ни в коем случае!
Я скачал ваш пакет, хочу его использовать, а он аварийно завершает работу системы в случае ошибки! Представьте, что поиск Яндекса так бы работал.

2021-05-23 12:21 UTC, DmitriyVTitov commented on 05-fifth-lesson/cmd/scanner/main.go
> +}
Столько вызовов функций и ни одного случая обработки ошибки! Так быть не должно.

2021-05-23 12:21 UTC, DmitriyVTitov commented on 05-fifth-lesson/cmd/scanner/main.go
> +func source() []crawler.Document {
что за имя "источник"? о чём оно должно говорить?

2021-05-24 18:31 UTC, DmitriyVTitov requested changes
Пока что обработку ошибок всё ещё не завезли )

2021-05-24 18:31 UTC, DmitriyVTitov commented on 05-fifth-lesson/cmd/scanner/main.go
> +	ind := index.Make(res)
Итак: получили ошибку при вызове dataSource() и что? Ничего, напечатали в консоль и всё. И продолжаем работать с результатом. В чём у вас разница в логике между наличием и отсутствием ошибки? То есть успешный и неуспешный путь один и тот же!
Кстати, функция, которая ничего не принимает, выглядит всегда подозрительно. В данном случае она должна была бы принимать массив ссылок и их обходить. И название было бы другим и более понятным.

2021-05-25 07:53 UTC, ImBigman commented on 05-fifth-lesson/cmd/scanner/main.go
> +	ind := index.Make(res)
Программа не перестает работать - просто она сканирует сайты, если с файлами работа завершилась с ошибкой. По ТЗ работа с файлами это только 1 из путей. Про пустой метод: передавать туда ссылки, чтобы внутри их же использовать в scan() - как-то странно, метод как развилка между источниками.

2021-05-25 19:26 UTC, DmitriyVTitov commented on 05-fifth-lesson/cmd/scanner/main.go
> +	ind := index.Make(res)
Я понимаю, что программа работает. Я вообще обычно не проверяю работоспособность, т.е. не запускаю приложение. Но вот кусок кода выше: при ошибке ничего не происходит, а так быть не должно.
Я умышленно остановил проверку здесь, потому что это явная ошибка в дизайне кода. И это надо исправить.
По поводу функции без аргументов:
`scan(urls []string) []docs` - всё понятно
`scan() []docs` - чтобы понять где функция берёт входные данные надо лезть в код.

Посмотрите определение функции в алгебре.

2021-05-25 22:34 UTC, DmitriyVTitov requested changes
Обработка ошибок не изменилась. Удачный и неудачный пути в main() совпадают.
И тут дело не в том, что что-то не работает, а в том, что код плохо спроектирован и логика не считывается. Требуется переработка.

2021-05-25 22:34 UTC, DmitriyVTitov commented on 05-fifth-lesson/cmd/scanner/main.go
> +	res, err := dataSource(resources)
На мой взгляд стало понятнее, как вам? Сигнатура функции легко читается.

2021-05-25 22:34 UTC, DmitriyVTitov commented on 05-fifth-lesson/cmd/scanner/main.go
> +	}
А вот это всё ещё нельзя назвать обработкой ошибки.

2021-05-25 22:34 UTC, DmitriyVTitov commented on 05-fifth-lesson/cmd/scanner/main.go
> +	}
else делает код трудночитаемым

2021-06-05 14:02 UTC, DmitriyVTitov approved these changes
OK, принимаю, но старайтесь избегать функций без аргументов. Иногда - ОК, но редко.

2021-06-05 14:02 UTC, DmitriyVTitov commented on 05-fifth-lesson/pkg/storage/storage.go
> +func Rec(docs []crawler.Document) (bool, error) {
Имя не особо удачное. Rec - запись (record).

2021-06-05 14:02 UTC, DmitriyVTitov commented on 05-fifth-lesson/pkg/storage/storage.go
> +func Rec(docs []crawler.Document) (bool, error) {
store, save и т.д.
Имена очень важны.

2021-06-05 14:02 UTC, DmitriyVTitov commented on 05-fifth-lesson/pkg/storage/storage.go
> +func Exrtact() ([]crawler.Document, error) {
Функция ничего не принимает. Откуда и что она будет "извлекать"?
Допустим, я хочу непосредственно указать имя файла, где я сохранил данные. Мне придется изменять код в этом пакете.
Нарушение OCP.

2021-06-05 14:02 UTC, DmitriyVTitov commented on 05-fifth-lesson/pkg/storage/storage.go
> +func Empty() bool {
Empty - пусто. А в описании совсем другое.

2021-06-05 14:02 UTC, DmitriyVTitov commented on 05-fifth-lesson/pkg/storage/storage.go
> +const path = "./store/scan_result.txt"
вот эти вещи следует передавать как аргументы функций, иначе пакет потребуется со временем изменить

2021-06-05 14:02 UTC, DmitriyVTitov commented on 05-fifth-lesson/cmd/scanner/main.go
> +		data, err = storage.Exrtact()
return storage.Extract()

2021-06-05 14:02 UTC, DmitriyVTitov commented on 05-fifth-lesson/cmd/scanner/main.go
> +		data, err = scan(m)
return scan(m)

2021-06-05 14:02 UTC, DmitriyVTitov commented on 05-fifth-lesson/cmd/scanner/main.go
> +			return result, err
в случае ошибки возвращайте значение по умолчанию
`return nil, err`

2021-06-06 08:25 UTC, merged